### ISSUE TITLE
Problems with start

### ISSUE THREAD

**Issue by PabloRodMen** [StarkBotsIndustries/ChannelBot#8]
Hello, 
I have configured the file and I have checked that I can connect with that user, but it is not working.

Pyromod is working! If you like pyromod, please star it at https://github.com/usernein/pyromod
Traceback (most recent call last):
  File "/ChannelBot/channelbot.py", line 23, in <module>
    app.start()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 74, in start
    await self.initialize()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 46, in initialize
    self.load_plugins()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 689, in load_plugins
    module = import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/ChannelBot/ChannelBot/add_channels.py", line 8, in <module>
    from ChannelBot.database.users_sql import add_channel as uac, remove_channel
  File "/ChannelBot/ChannelBot/database/users_sql.py", line 17, in <module>
    Users.__table__.create(checkfirst=True)
TypeError: create() missing 1 required positional argument: 'bind'

Thanks

**Comment by ShivangKakkar** [comment]
This is a really outdated repository. I would suggest you find another one. Pyrogram, Pyromod and SQLAlchemy versions used here are old and the code hasn't been updated to meet the new changes
